export default [
  {
    id: "Federal",
    parentId: null,
    layerOrder: 17,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "Federal",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "BLM",
    parentId: "Federal",
    layerOrder: 3,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "BLM",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "blm_states",
    parentId: "BLM",
    layerOrder: 145,
    serviceType: "ArcGISImage",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "States",
    description: "States",
    url:
      "https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer",
    layerList: "0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "blm_sections",
    parentId: "BLM",
    layerOrder: 145,
    serviceType: "ArcGISImage",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "Sections",
    description: "Sections",
    url:
      "https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer",
    layerList: "1",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "blm_townships",
    parentId: "BLM",
    layerOrder: 145,
    serviceType: "ArcGISImage",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "Townships",
    description: "Townships",
    url:
      "https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer",
    layerList: "2",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: 4000000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "blm_intersected",
    parentId: "BLM",
    layerOrder: 145,
    serviceType: "ArcGISImage",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "Intersected",
    description: "Intersected ",
    url:
      "https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer",
    layerList: "3",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: 200000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "Census",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "Census",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "congress-116",
    parentId: "Census",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "116th Congressional Districts",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:congress-116",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "tl-county",
    parentId: "Census",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "County Boundaries",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:tl-county",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "tl-state",
    parentId: "Census",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "State Boundaries",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:tl-state",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "DOI",
    parentId: "Federal",
    layerOrder: 3,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "DOI",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: "",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "BIA",
    parentId: "DOI",
    layerOrder: 3,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "BIA",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: "",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "bia-lar",
    parentId: "BIA",
    layerOrder: 145,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "Land Area Representations (LARs)",
    description: "Land Area Representations (LARs)",
    url: "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer",
    layerList: "show:0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "bia-supp-lar",
    parentId: "BIA",
    layerOrder: 145,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "Supplemental LAR",
    description: "Supplemental LAR",
    url: "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer",
    layerList: "1",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer/1",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "bia-al-nat-corp",
    parentId: "BIA",
    layerOrder: 145,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "Alaskan Native Corportations",
    description: "Alaskan Native Corportations",
    url: "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer",
    layerList: "2",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer/2",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "bia-al-nat-vill",
    parentId: "BIA",
    layerOrder: 145,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "Alaskan Native Villages",
    description: "Alaskan Native Villages",
    url: "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer",
    layerList: "3",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer/3",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "bia-tri-stat-area",
    parentId: "BIA",
    layerOrder: 145,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "Tribal Statistical Area",
    description: "Tribal Statistical Area",
    url: "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer",
    layerList: "4",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer/4",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "bia-regions",
    parentId: "BIA",
    layerOrder: 145,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "BIA Regions",
    description: "BIA Regions",
    url: "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer",
    layerList: "5",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://biamaps.doi.gov/server/rest/services/IndianLands1/MapServer/5",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "DOT",
    parentId: "Federal",
    layerOrder: 10,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "DOT",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "dot-commfol",
    parentId: "DOT",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Fiber Optic Lines",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:commfol",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "dot-commrfol",
    parentId: "DOT",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Regional Fiber Optic Lines",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:commrfol",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "dot-engoilgaspipe",
    parentId: "DOT",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Oil and Gas Pipelines",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:engoilgaspipe",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "dot-engtransline",
    parentId: "DOT",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Electric Transmission Lines",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:engtransline",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "EPA",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "EPA",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "epa-regulated-facilities",
    parentId: "EPA",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Regulated Facilities",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:epa-regulated-facilities",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "FEMA",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "FEMA",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "fema_nfhl_avail",
    parentId: "FEMA",
    layerOrder: 100,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "National Flood Hazard Layer Availability",
    description: "This data shows availability of NFHL data by jurisdiction.",
    url:
      "https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer",
    layerList: "show: 0",
    params: {
      transparent: true,
      ratio: 1,
    },
    attributions: null,
    minscale: 250000,
    maxscale: null,
    metadataUrl:
      "https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer/0",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend:
      "https://maps.crrel.usace.army.mil/graphics/orm_legend_items/fema_nfhl_avail.jpg",
  },
  {
    id: "fema_nfhl_zones",
    parentId: "FEMA",
    layerOrder: 101,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "Flood Hazard Zones",
    description: "This data shows regulatory flood zones designated by FEMA. ",
    url:
      "https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer",
    layerList: "show: 28",
    params: {
      transparent: true,
      ratio: 1,
    },
    attributions: null,
    minscale: null,
    maxscale: 50000,
    metadataUrl:
      "https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer/28",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend:
      "https://maps.crrel.usace.army.mil/graphics/orm_legend_items/fema_nfhl.jpg",
  },
  {
    id: "femaq3",
    parentId: "FEMA",
    layerOrder: 1,
    serviceType: "WMS",
    identifyType: null,
    tiled: 0,
    displayName: "FEMA 100/500 Yr Floodplains",
    description: null,
    url: "http://hazards.fema.gov/wmsconnector/wmsconnector/Servlet/NFHL?",
    layerList: "Flood_Hazard_Zones_General",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 300000,
    metadataUrl: null,
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "fema_100_yr_flood",
    parentId: "FEMA",
    layerOrder: 100,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "FEMA 100yr Flood Zones",
    description:
      "Displays 100-year flood zones within the U.S. The 100-year flood is referred to as the 1% annual exceedance probability flood, since it is a flood that has a 1% chance of being equaled or exceeded in any single year.",
    url:
      "http://maps3.arcgisonline.com/ArcGIS/rest/services/A-16/FEMA_100-Year_Flood_Zones_in_the_USA/MapServer",
    layerList: "show:1",
    params: {
      transparent: true,
      ratio: 1,
    },
    attributions: null,
    minscale: 0,
    maxscale: 3000000,
    metadataUrl:
      "http://maps3.arcgisonline.com/ArcGIS/rest/services/A-16/FEMA_100-Year_Flood_Zones_in_the_USA/MapServer",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend:
      "http://maps.crrel.usace.army.mil:7778/graphics/fema_floodplains.png",
  },
  {
    id: "natatlas",
    parentId: "Federal",
    layerOrder: 40,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "National Atlas",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "nat-atlas-mine",
    parentId: "natatlas",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Abandoned Mines",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:mine",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "nat-atlas-counties",
    parentId: "natatlas",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Counties",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:us_county",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "fedland",
    parentId: "natatlas",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Federal Land",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:fedland",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "triballands",
    parentId: "natatlas",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Indian Lands",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:tribballands",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "nuclear",
    parentId: "natatlas",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Nuclear Reactor Facilities",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:nuclear",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "plss",
    parentId: "natatlas",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Public Land Survey System, National Atlas",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:plss",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "volcano",
    parentId: "natatlas",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Volcanoes, National Atlas",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:volcano",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "Fed-NCED",
    parentId: "Federal",
    layerOrder: 10,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "NCED",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "bia-nced",
    parentId: "Fed-NCED",
    layerOrder: 145,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "National Conservation Easement Database",
    description: "National Conservation Easement Database",
    url:
      "https://www.sciencebase.gov/arcgis/rest/services/Catalog/51df3e34e4b0d24b0f89dd7e/MapServer",
    layerList: "show:0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://www.sciencebase.gov/arcgis/rest/services/Catalog/51df3e34e4b0d24b0f89dd7e/MapServer",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "Fed-NOAA",
    parentId: "Federal",
    layerOrder: 10,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "NOAA",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "noaa_eez",
    parentId: "Fed-NOAA",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Exclusive Economic Zones",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:noaa_eez",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "marinesanc",
    parentId: "Fed-NOAA",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "National Marine Sanctuaries",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:marinesanc",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "crit_hab_linepoly",
    parentId: "Fed-NOAA",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "NMFS Critical Habitats",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:crit_hab_linepoly",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "crit_hab_poly",
    parentId: "Fed-NOAA",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "NMFS Critical Habitats - polygon",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:crit_hab_poly",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "nmfs_ranges",
    parentId: "Fed-NOAA",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "NMFS Ranges",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:nmfs_ranges",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "nmfs_efh",
    parentId: "Fed-NOAA",
    layerOrder: 2,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "NMFS Essential Fish Habitat",
    description: null,
    url:
      "https://idpgis.ncep.noaa.gov/arcgis/rest/services/NMFS/EFH_Only/MapServer",
    layerList: "show:0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 1000,
    maxscale: 20000000,
    metadataUrl:
      "https://idpgis.ncep.noaa.gov/arcgis/rest/services/NMFS/EFH_Only/MapServer",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "nmfs_efh_protected",
    parentId: "Fed-NOAA",
    layerOrder: 2,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "NMFS EFH Areas Protected from Fishing",
    description: null,
    url:
      "https://idpgis.ncep.noaa.gov/arcgis/rest/services/NMFS/EFHAreasProtectedFromFishing/MapServer",
    layerList: "0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 1000,
    maxscale: 20000000,
    metadataUrl:
      "https://idpgis.ncep.noaa.gov/arcgis/rest/services/NMFS/EFHAreasProtectedFromFishing/MapServer",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "nmfs_habitat_concern",
    parentId: "Fed-NOAA",
    layerOrder: 2,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "NMFS Habitat Areas of Particular Concern",
    description: null,
    url:
      "https://idpgis.ncep.noaa.gov/arcgis/rest/services/NMFS/HAPC/MapServer",
    layerList: "0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 1000,
    maxscale: 20000000,
    metadataUrl:
      "https://idpgis.ncep.noaa.gov/arcgis/rest/services/NMFS/HAPC/MapServer",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "noaa_tides",
    parentId: "Fed-NOAA",
    layerOrder: 131,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Tide and Current Gages",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:noaa_tides",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "Fed-NPS",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "NPS",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "histprop",
    parentId: "Fed-NPS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Historic Properties",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:histprop",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "NRCS",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "NRCS",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "NRCS-Soil-Data",
    parentId: "NRCS",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "NRCS Soil Data",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "nrsoil_global_soil_regions",
    parentId: "NRCS-Soil-Data",
    layerOrder: 30,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "Global Soil Regions",
    description:
      "This layer shows the Global Soil Regions map by the United States Department of Agricultures Natural Resources Conservation Service.  The data and symbology are based on a reclassification of the FAO-UNESCO Soil Map of the World combined with a soil climate map. The soils data is symbolized to show the distribution of the 12 soil orders according to Soil Taxonomy.",
    url:
      "http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/Soil_Survey_Map/MapServer",
    layerList: "show:2",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/Soil_Survey_Map/MapServer/2",
    opacity: 0.6,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "nrsoil_soil_survey_geographic",
    parentId: "NRCS-Soil-Data",
    layerOrder: 10,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "Soil Survey Geographic",
    description: "",
    url:
      "http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/Soil_Survey_Map/MapServer",
    layerList: "show:0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/Soil_Survey_Map/MapServer/0",
    opacity: 0.6,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "nrsoil_state_soil_geographic",
    parentId: "NRCS-Soil-Data",
    layerOrder: 20,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "State Soil Geographic",
    description: "",
    url:
      "http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/Soil_Survey_Map/MapServer",
    layerList: "show:1",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/Soil_Survey_Map/MapServer/1",
    opacity: 0.6,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "US-Coast-Guard",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "US Coast Guard",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "coast-guard-districts",
    parentId: "US-Coast-Guard",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Coast Guard Districts",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:cg-districts",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "USDA",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "USDA",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "WBDLine",
    parentId: "USDA",
    layerOrder: 5,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "WBDLine",
    description: null,
    url: "https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer",
    layerList: "0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/0",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "10-digitHU",
    parentId: "USDA",
    layerOrder: 51,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "10-digit HU (Watershed)",
    description: null,
    url: "https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer",
    layerList: "5",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/5",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "HU-boundaries",
    parentId: "USDA",
    layerOrder: 51,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "HU Seamless Boundaries 2 to 14 Digits",
    description: null,
    url: "https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer",
    layerList: "1,2,3,4,5,6,7",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/5",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "mlra",
    parentId: "USDA",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Major Land Resource Area",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:mlra",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "USFS",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "USFS",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "USFS-wild-and-scenic-rivers",
    parentId: "USFS",
    layerOrder: 51,
    serviceType: "ArcGIS",
    identifyType: "arcgisrest",
    tiled: 0,
    displayName: "Wild and Scenic Rivers",
    description: null,
    url:
      "https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_WildScenicRiverSegments_01/MapServer",
    layerList: "0,1",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_WildScenicRiverSegments_01/MapServer",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "USFWS-fed",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "USFWS",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "USFWS-crit-hab-lin-feat",
    parentId: "USFWS-fed",
    layerOrder: 145,
    serviceType: "EsriFeatureService",
    identifyType: null,
    tiled: 0,
    displayName: "Critical Habitat - Linear Features - Final",
    description: "Critical Habitat - Linear Features - Final",
    url:
      "https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/USFWS_Critical_Habitat/FeatureServer",
    layerList: "0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/USFWS_Critical_Habitat/FeatureServer",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "USFWS-crit-hab-poly-feat",
    parentId: "USFWS-fed",
    layerOrder: 145,
    serviceType: "EsriFeatureService",
    identifyType: null,
    tiled: 0,
    displayName: "Critical Habitat - Polygon Features - Final",
    description: "Critical Habitat - Polygon Features - Final",
    url:
      "https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/USFWS_Critical_Habitat/FeatureServer",
    layerList: "1",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/USFWS_Critical_Habitat/FeatureServer",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "USFWS-crit-hab-lin-feat-prop",
    parentId: "USFWS-fed",
    layerOrder: 145,
    serviceType: "EsriFeatureService",
    identifyType: null,
    tiled: 0,
    displayName: "Critical Habitat - Linear Features - Proposed",
    description: "Critical Habitat - Linear Features - Proposed",
    url:
      "https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/USFWS_Critical_Habitat/FeatureServer",
    layerList: "2",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/USFWS_Critical_Habitat/FeatureServer",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "USFWS-crit-hab-poly-feat-prop",
    parentId: "USFWS-fed",
    layerOrder: 145,
    serviceType: "EsriFeatureService",
    identifyType: null,
    tiled: 0,
    displayName: "Critical Habitat - Polygon Features - Proposed",
    description: "Critical Habitat - Polygon Features - Proposed",
    url:
      "https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/USFWS_Critical_Habitat/FeatureServer",
    layerList: "3",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/USFWS_Critical_Habitat/FeatureServer",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "USFWS-wetlands",
    parentId: "USFWS-fed",
    layerOrder: 145,
    serviceType: "EsriFeatureService",
    identifyType: null,
    tiled: 0,
    displayName: "Wetlands",
    description: "Wetlands",
    url: "https://www.fws.gov/wetlands/arcgis/rest/services/Wetlands/MapServer",
    layerList: "0",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://www.fws.gov/wetlands/arcgis/rest/services/Wetlands/MapServer",
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: "esri",
  },
  {
    id: "USGS",
    parentId: "Federal",
    layerOrder: 15,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "USGS",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "quad24",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "24K Quad",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:quad24",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "quad100",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "100K Quad",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:quad100",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "quad250",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "250K Quad",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:quad250",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "usgs_nlcd_2011_landcover",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "GEOSERVER",
    tiled: 0,
    displayName: "2011 NLCD Land Cover",
    description: null,
    url:
      "https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2011_Land_Cover_L48/ows",
    layerList: "NLCD_2011_Land_Cover_L48",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "usgs_nlcd_2011_landcover_ak",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "GEOSERVER",
    tiled: 0,
    displayName: "2011 NLCD Land Cover Alaska",
    description: null,
    url:
      "https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2011_Land_Cover_AK/ows",
    layerList: "NLCD_2011_Land_Cover_AK",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "NLCD_2011_Impervious_L48",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "GEOSERVER",
    tiled: 0,
    displayName: "2011 Impervious Surfaces",
    description: null,
    url:
      "https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2011_Impervious_L48/ows",
    layerList: "NLCD_2011_Impervious_L48",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "NLCD_2011_Impervious_AK",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "GEOSERVER",
    tiled: 0,
    displayName: "2011 Impervious Surfaces Alaska",
    description: null,
    url:
      "https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2011_Impervious_AK/ows",
    layerList: "NLCD_2011_Impervious_AK",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "usgs_nlcd_2016_landcover",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "GEOSERVER",
    tiled: 0,
    displayName: "2016 NLCD Land Cover",
    description: null,
    url:
      "https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2016_Land_Cover_L48/ows",
    layerList: "NLCD_2016_Land_Cover_L48",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "usgs_nlcd_2016_landcover_ak",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "GEOSERVER",
    tiled: 0,
    displayName: "2016 NLCD Land Cover Alaska",
    description: null,
    url:
      "https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2016_Land_Cover_AK/ows",
    layerList: "NLCD_2016_Land_Cover_AK",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "NLCD_2016_Impevious_L48",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "GEOSERVER",
    tiled: 0,
    displayName: "2016 Impervious Surfaces",
    description: null,
    url:
      "https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2016_Impervious_L48/ows",
    layerList: "NLCD_2016_Impervious_L48",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "NLCD_2016_Impevious_AK",
    parentId: "USGS",
    layerOrder: 130,
    serviceType: "WMS",
    identifyType: "GEOSERVER",
    tiled: 0,
    displayName: "2016 Impervious Surfaces Alaska",
    description: null,
    url:
      "https://www.mrlc.gov/geoserver/mrlc_display/NLCD_2016_Impervious_AK/ows",
    layerList: "NLCD_2016_Impervious_AK",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "natmap_hucs_high_res",
    parentId: "USGS",
    layerOrder: 85,
    serviceType: "ArcGISImage",
    identifyType: null,
    tiled: 0,
    displayName: "USGS NHD",
    description:
      "This uses the data from The National Map web services from USGS",
    url: "https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer",
    layerList: "show:0,1,2,3,4,5,6,7,8,9,10",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl:
      "https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer",
    opacity: 0.8,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
];
