export default [
  {
    id: "reg",
    parentId: null,
    layerOrder: 5,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "Regulatory",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "watersmap",
    parentId: "reg",
    layerOrder: 20,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "ORM Aquatic Resources",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-wpc/wms",
    layerList: "orm-wpc:ORMARs",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "watersmap-no-labels",
    parentId: "reg",
    layerOrder: 20,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "ORM Aquatic Resources - no labels",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-wpc/wms",
    layerList: "orm-wpc:ORMARs-no-labels",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "projectmap",
    parentId: "reg",
    layerOrder: 1,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "ORM Project Locations",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-wpc/wms",
    layerList: "orm-wpc:ORMProjectsAll",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 300000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
];
