export default [
  {
    id: "statesFolder",
    parentId: null,
    layerOrder: 5,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "States",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv",
    parentId: "statesFolder",
    layerOrder: 7,
    serviceType: "Folder",
    identifyType: null,
    tiled: 0,
    displayName: "West Virginia",
    description: null,
    url: null,
    layerList: null,
    params: null,
    attributions: null,
    minscale: null,
    maxscale: null,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    collapsed: 1,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-am-lines",
    parentId: "wv",
    layerOrder: 110,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Abandoned Mines (line)",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-abandoned-mines-lines",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-am-points",
    parentId: "wv",
    layerOrder: 111,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Abandoned Mines (point)",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-abandoned-mines-points",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-am-polygon",
    parentId: "wv",
    layerOrder: 112,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Abandoned Mines (polygon)",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-abandoned-mines-polygons",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-coal-permit",
    parentId: "wv",
    layerOrder: 113,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "Coal Permit Boundary",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-coal-permit-bnd",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-dams",
    parentId: "wv",
    layerOrder: 114,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Dams gt 1st Order",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-dams",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-NPDES",
    parentId: "wv",
    layerOrder: 115,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia EPA Facilities - NPDES",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-epa-npdes",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-nonNPDES",
    parentId: "wv",
    layerOrder: 116,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia EPA Facilities - non NPDES",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-epa-nonnpdes",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-fhp",
    parentId: "wv",
    layerOrder: 118,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Forestry Harvest Permits",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-forestharvest-permit",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-iw",
    parentId: "wv",
    layerOrder: 121,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Impaired Waters - 2008",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-impairedwaters-2008",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-is",
    parentId: "wv",
    layerOrder: 122,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Impounded Streams",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-impounded-stream",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-mpb",
    parentId: "wv",
    layerOrder: 122,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Mining Permits Bounds",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-coal-permit-bnd",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-ms",
    parentId: "wv",
    layerOrder: 123,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Mining Surface",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-mining-surface",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-og",
    parentId: "wv",
    layerOrder: 124,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Oil Gas",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-oilgas",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-roads",
    parentId: "wv",
    layerOrder: 125,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Roads x NHD",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-roads",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-structures",
    parentId: "wv",
    layerOrder: 126,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Structures SAMB",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-structures-samb",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
  {
    id: "wv-valley-fills",
    parentId: "wv",
    layerOrder: 126,
    serviceType: "WMS",
    identifyType: "ORM-GEOSERVER",
    tiled: 0,
    displayName: "West Virginia Valley Fills",
    description: null,
    url: "https://orm-corpsmap.usace.army.mil:8443/geoserver/orm-prod-ms/wms",
    layerList: "orm-prod-ms:wv-vallfills",
    params: {
      transparent: true,
    },
    attributions: null,
    minscale: 0,
    maxscale: 500000,
    metadataUrl: null,
    opacity: 1,
    visible: 0,
    labelDefault: 0,
    labelEnabled: 0,
    legend: null,
  },
];
